language: node_js
node_js: 8
script: npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: aueSgwwoITi+TOoXFvWP/QZljTcqCm+YtbGGAct4EcvQVtnzTabRpQLm/soUFFTWpEd3MyjNIWUbonpsEw0cZzeiVFpV3j4OLsGM8znSNbFG/brOffJEemOhmLU1hgbB445BmNIbm2G1f9agg1DLNmBNIkrWXRfkTccPRwtRoyxOJmUkt0gUHH/udogtdRDVVnrni2lqn3ertU/Gp6irHre43m7a/+z4LPDdOYvfVoDopFtU40IaZodsxz7oGkKyuBXUvdE7cNDsn0fs7b0IbOmbDedpYlKEG2JYSefVknonGlwUxeKqIrC8SbURv/qEmMOp3V0oZwI1b/zigUcOhHCTQQWSiBrH1HRuftFNtcrvZSP+XvtSGNCm6qONDTJwpoP2BtV2kSR8WOKZWXIopeG89Xh9srtF0k951BFQF+5m6D49vqF094V1yXKe3hDVjUksJwjeQ/6LT8NJbKoLCFrLDxwxKhZP1+dKsvPvx47O5DQjmfkQGpw5/L44y8ZRZUlXxXKyLePeUVJJm3hbe+GYGgOMHjMdbud94bS7DgGFSSvF9YEM4qgnQiU3hb3xjttRHukYrShDXdrgV33yVZpNaixawvnkALz7sZ38jSj2OEs2zyKz7oLukjLNTlsSQ/7qypZzJE79GhXNsprdYl19ErC9TpHXyoS5rshV3vU=
