language: node_js
node_js: 8
script: npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: L8YfxnXwe4ayS11COci85GVylIy4hzbuuKEN15UPMp/ioMafMCqCyTzPoFL1oSzW01NTBMFvHPgtdRCwEN+cqI2tncqhGGEEjExeWZoa403XZEZHh1aumfM7VMuqElv9s5wu+Rc6z19K/MYYenIG2U3CG7uQO5eR8benn/TaTYRvnvABsJXjXe1oYK0EdD1DaisZHuc7nJVASvDwq0DmndeyBUuL/Hzp5ifJfIQaK5+xbvcr2DXXsmDeBqxteVmeoi26id8RANf4uPbALeTuBoxaVWv89ov3NG1oBunKORA9OaaTDQ/5l9UzNA2G+SXbcXoUA1j+4W5IcD3Qmf32W2hZTmiJEMYd0lMV4J8Bze4mLb6N7Kt9Aaags4HsC1JFTSpf4xvuaUhK34WMGNW7bvVeL7X8Cifl/77DSfOGhNJXCskvATb5N7pcjuIaJ7TsEy8TPLEPxptTfFKtZDp5zYPcmGy/aJbLA8tjx4Tx6eDSLCvO4/AhwALh4jz00fUHHUdhjs7MwbiSPJPQQcYee+WRk61Md0zFTlXSfGOEwgg6iqjaRQ1GqgQ/bLosrE76Q0TvFlB0g6uMrZNjseuaLs78cmoCcSIkWNLmh3bvh7tMS6iqb0+kH6Pumgs7w70btbtYr7KZ19lQz3OGeprazgAGI/rqemcae6lRUR9RdVc=